# tests/test_publish.py

import sys
import os
from dotenv import load_dotenv

# Extend system path to access publisher module
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from content_generation.publisher import publish_post

# Load environment variables
load_dotenv()

wp_site = os.getenv("WP_SITE")
wp_user = os.getenv("WP_USER")
wp_app_password = os.getenv("WP_APP_PASSWORD")

# Post content
title = "🚀 Test Post from Smart Content System"
content = "This is a test post generated by the Smart Content System. If you see this, it worked!"

# Publish
publish_post(wp_site, wp_user, wp_app_password, title, content, status="draft")